package dev.frost.obfuscator.jni.compiler;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Collects staged C++ source files in deterministic order.
 */
public final class SourceCollector {
    public List<Path> collect(SourceLayout layout) throws IOException {
        List<Path> sources = new ArrayList<>();
        sources.add(layout.root().resolve("bootstrap.cpp"));
        addDirectorySources(sources, layout.runtimeDirectory());
        addDirectorySources(sources, layout.classesDirectory());
        return List.copyOf(sources);
    }

    public List<Path> collectForBuild(SourceLayout layout, boolean unityBuild) throws IOException {
        List<Path> sources = collect(layout);
        if (!unityBuild) {
            return sources;
        }
        return List.of(writeUnitySource(layout, sources));
    }

    private Path writeUnitySource(SourceLayout layout, List<Path> sources) throws IOException {
        Path unitySource = layout.root().resolve("frostjni_unity.cpp");
        StringBuilder builder = new StringBuilder();
        builder.append("// Generated by FrostJNI fast unity build.\n");
        for (Path source : sources) {
            builder.append("#include \"")
                    .append(layout.root().relativize(source).toString().replace('\\', '/'))
                    .append("\"\n");
        }
        Files.writeString(unitySource, builder.toString());
        return unitySource;
    }

    private void addDirectorySources(List<Path> sources, Path directory) throws IOException {
        try (var stream = Files.list(directory)) {
            stream.filter(path -> path.getFileName().toString().endsWith(".cpp"))
                    .sorted(Comparator.comparing(Path::toString))
                    .forEach(sources::add);
        }
    }
}


