package dev.frost.ir.bytecode;

public enum ImportCapability {
    CONTROL_FLOW,
    EXCEPTIONAL_CONTROL_FLOW,
    METHOD_PARAMETERS,
    BIDIRECTIONAL_SOURCE_MAP,
    PRESERVED_ASM_SNAPSHOT,
    TYPED_STACK_SSA,
    FRAME_STATES,
    LOWERABLE_AFTER_MUTATION,
    LEGACY_SUBROUTINES_INLINED
}
